### ISSUE TITLE
The table does not exist and Array to string conversion

### ISSUE THREAD

**Issue by Djive** [boldenamsterdam/openweather#1]
Tried using both twig functions and http requests, but getting this error:

2019-01-25 11:23:40 [-][1][2f9569d2df49bc1fb722275fc67f5be0][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: The table does not exist: {{%open_weather_entries%}} in /home/brinjeinfo/vendor/yiisoft/yii2/db/ActiveRecord.php:387

When using `craft.openWeather.defaultLocation()`, then I am getting this error:

2019-01-25 11:25:03 [-][1][2f9569d2df49bc1fb722275fc67f5be0][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /home/brinjeinfo/storage/runtime/compiled_templates/eb/eb1205d87632124d0dc256ecf8c6df63594c76c8ef363b5808d21fe977bc825a.php:64

API key is registered and filled in.
Refresh interval is 720.
Latitude and longitude for default location are both filled in.
In database, I can see "craft_open_weather_entries" table but its empty.

If I try to get the info directly, then it works:

request:
https://api.openweathermap.org/data/2.5/weather?q=London,uk&appid=my-api-key

response:
{"coord":{"lon":-0.13,"lat":51.51},"weather":[{"id":721,"main":"Haze","description":"haze","icon":"50d"},{"id":701,"main":"Mist","description":"mist","icon":"50d"}],"base":"stations","main":{"temp":280.16,"pressure":1014,"humidity":100,"temp_min":279.15,"temp_max":281.15},"visibility":5000,"wind":{"speed":4.6,"deg":250},"clouds":{"all":75},"dt":1548411600,"sys":{"type":1,"id":1414,"message":0.0041,"country":"GB","sunrise":1548402515,"sunset":1548434264},"id":2643743,"name":"London","cod":200}

PHP version 7.2.10
Craft Pro 3.0.37
This is a multisite setup.

Looking forward to using your addon, thanks!

**Comment by boldenamsterdam** [comment]
Hi Djive,

It looks like the table `open_weather_entries` is not created. Can you double check if in the db the table `open_weather_entries` exists? Did the installation of the plugin completed without errors?
Can you try to remove and install again the plugin?

Let me know!

**Comment by Djive** [comment]
I edited my issue just a few minutes ago to write this info :)
In database, I can see "craft_open_weather_entries" table but its empty.

I will try to reinstall now.

**Comment by Djive** [comment]
Craft is now updated to newest version - Craft Pro 3.1.5

Removed the plugin completly, reinstalled it and entered all the settings.
Getting same error messages as before.
In database, I can see "craft_open_weather_entries" table but its empty.

**Comment by brettburwell** [comment]
I'm seeing the same issue. I checked the DB and can see the `craft_open_weather_entries` table. I also tried uninstalling and starting from scratch with the same result.

**Comment by boldenamsterdam** [comment]
Ah, I see the issue.
You are probably doing something like 
`{% set latlon = craft.openWeather.defaultLocation() %}`
`{{ latlon }`
In that case `latlon` is an array so twig cannot print it.
Instead you can use `{{ latlon.latitude }}` and `{{ latlon.longitude }}` to print them in your twig templates.

Let me know!

**Comment by Djive** [comment]
Tried this now:

```
{% set latlon = craft.openWeather.defaultLocation() %}
{{ latlon.latitude }}
{{ latlon.longitude }}
```

Your code indeed returns latitude and longidute but when I try to use them in the plugin, via twig function

`{{ craft.openWeather.simplified(latlon.latitude, latlon.longitude) }}`

 I get this error as a response:

2019-02-07 11:53:23 [-][-][8d898e673aa299fe681c2005282dde78][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: The table does not exist: {{%open_weather_entries%}} in /home/site/vendor/yiisoft/yii2/db/ActiveRecord.php:387

In my original attempt, the only difference was that I was pulling latitude and longitude from globals, like this:

`{{ craft.openWeather.simplified(globalfield.latitude, globalfield.longitude) }}`

**Comment by boldenamsterdam** [comment]
I cannot seem to reproduce the same error. If I use your code I get the error of "array to string conversion". Do use comma "," or dot "." as decimal separator? (should be dot)
I would suggest to use the twig commands as follow by printing a property and not an array:
`
{% set result = craft.openWeather.simplified(latlon.latitude, latlon.longitude) %}
{{ result.temperature }}
`

Did this help?

**Comment by Djive** [comment]
Tried exacly with your code:

```
{% set latlon = craft.openWeather.defaultLocation() %}
{% set result = craft.openWeather.simplified(latlon.latitude, latlon.longitude) %}
{{ result.temperature }}
```
Got this error:

2019-02-07 17:56:40 [-][-][8d898e673aa299fe681c2005282dde78][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: The table does not exist: {{%open_weather_entries%}} in /home/site/vendor/yiisoft/yii2/db/ActiveRecord.php:387

In the plugin, coordinates are entered like this:
Latitude: 45.814912
Longitude: 15.978515

PHP version 7.2.10
Craft Pro 3.1.8
This is a multisite setup.

**Comment by WilkoAD** [comment]
I was having the InvalidConfigException issue too - I changed `{{%open_weather_entries%}}` to `{{%open_weather_entries}}` in OpenWeatherEntryRecord.php and that seems to have resolved the issue.

**Comment by boldenamsterdam** [comment]
Hi all,

There is a new release which fixes this problem. @Djive let me know if that fixes your problem.

**Comment by Djive** [comment]
Its working now.
Thanks!
